/** PRD 缺口验收清单 — gaps.acceptance.test.ts */

export interface GapCase {
  id: string;
  ref: string;
  title: string;
  /** pass | gap-tracker (未实现但记录) | live-api */
  kind: "pass" | "gap-tracker" | "live-api";
}

export const GAP_CASES: GapCase[] = [
  { id: "GAP-HTTP-01", ref: "stream API", title: "POST /api/chat/stream SSE 契约", kind: "pass" },
  { id: "GAP-Q1", ref: "05-chat-qa Q1", title: "新建对话默认 metadata", kind: "pass" },
  { id: "GAP-Q1b", ref: "05-chat-qa Q1 §5.7", title: "空状态含理财助手文案", kind: "pass" },
  { id: "GAP-Q3", ref: "05-chat-qa Q3", title: "联网检索 citations ≤5", kind: "live-api" },
  { id: "GAP-Q4", ref: "05-chat-qa Q4", title: "Handoff 跳转卡 SSE", kind: "pass" },
  { id: "GAP-Q5", ref: "05-chat-qa Q5", title: "Handoff 卡片 UI + 暂不", kind: "pass" },
  { id: "GAP-Q5b", ref: "05-chat-qa Q5b", title: "Handoff 后新问题 simple_qa", kind: "pass" },
  { id: "GAP-Q5c", ref: "05-chat-qa Q5c", title: "口头「好的」不 handoff", kind: "pass" },
  { id: "GAP-Q7", ref: "05-chat-qa Q7", title: "vision_parse 工具 stub", kind: "pass" },
  { id: "GAP-Q8", ref: "05-chat-qa Q8", title: "handoff_autostart 空内容准入", kind: "pass" },
  { id: "GAP-Q9", ref: "05-chat-qa Q9", title: "停止生成 MSG-STOPPED", kind: "pass" },
  { id: "GAP-Q10", ref: "05-chat-qa Q10", title: "模型未就绪禁用输入", kind: "pass" },
  { id: "GAP-Q11", ref: "05-chat-qa Q11", title: "Vision 槽位可配置", kind: "pass" },
  { id: "GAP-Q12", ref: "05-chat-qa Q12", title: "chat / 仅 web_search+vision_parse", kind: "pass" },
  { id: "GAP-Q13", ref: "05-chat-qa Q13", title: "橙点 metadata 条件", kind: "pass" },
  { id: "GAP-Q14", ref: "05-chat-qa Q14", title: "大图 ERR-IMAGE-SIZE", kind: "pass" },
  { id: "GAP-S12", ref: "s12 workflow_tasks", title: "workflow_tasks 落盘", kind: "pass" },
  { id: "GAP-S13", ref: "s13 background_jobs", title: "background_jobs 写入与后台报告", kind: "pass" },
  { id: "GAP-HANDOFF-01", ref: "05-chat-shared §5.10.1", title: "POST /api/handoff/prepare", kind: "pass" },
  { id: "GAP-PROFILE", ref: "06-profile", title: "profile scene Harness 闭环", kind: "pass" },
  { id: "GAP-PROFILE-READ", ref: "06-profile §6.0.1", title: "profile_read 工具", kind: "pass" },
  { id: "GAP-PROFILE-EMPTY", ref: "06-profile §6.11 EMPTY-UI-01", title: "profile Tab 空状态", kind: "pass" },
  { id: "GAP-Q4b", ref: "05-chat-qa Q4 E2E", title: "Handoff 前往 + autostart", kind: "live-api" },
  { id: "GAP-PROFILE-GOAL", ref: "06-profile §6.2", title: "goal_constraint propose 校验", kind: "pass" },
  { id: "GAP-PROFILE-PUBLISH", ref: "06-profile §6.2.8", title: "report_publish 工具路由", kind: "pass" },
  { id: "GAP-PLAN-EMPTY", ref: "07-allocation-plan §7.9", title: "plan Tab 空状态 N 分支", kind: "pass" },
  { id: "GAP-PLAN-READ", ref: "07-allocation-plan §7.0", title: "plan_read 工具", kind: "pass" },
  { id: "GAP-PLAN-VALIDATE", ref: "07-allocation-plan §7.4", title: "plan_allocation/detail 校验", kind: "pass" },
  { id: "GAP-PLAN-SCENE", ref: "07-allocation-plan", title: "plan scene Harness 闭环", kind: "pass" },
  { id: "GAP-PLAN-PUBLISH", ref: "07-allocation-plan §7.4", title: "plan report_publish 路由", kind: "pass" },
  { id: "GAP-PLAN-L0", ref: "07-allocation-plan §7.1", title: "plan L0 stub 基金池校验", kind: "pass" },
  { id: "GAP-PORT-EMPTY", ref: "08-portfolio §8.8", title: "portfolio Tab 空状态 A/B 分支", kind: "pass" },
  { id: "GAP-PORT-READ", ref: "08-portfolio §8.1", title: "holdings_read 工具", kind: "pass" },
  { id: "GAP-PORT-VALIDATE", ref: "08-portfolio §8.9", title: "holdings propose 校验", kind: "pass" },
  { id: "GAP-PORT-SCENE", ref: "08-portfolio", title: "portfolio scene Harness 闭环", kind: "pass" },
  { id: "GAP-PORT-PUBLISH", ref: "08-portfolio §8.4", title: "portfolio report_publish 路由", kind: "pass" },
  { id: "GAP-FUND-EMPTY", ref: "09-fund §9.1.0c", title: "fund Tab 空状态", kind: "pass" },
  { id: "GAP-FUND-LOOKUP", ref: "09-fund", title: "fund_lookup stub", kind: "pass" },
  { id: "GAP-FUND-SCENE", ref: "09-fund", title: "fund scene Harness 闭环", kind: "pass" },
  { id: "GAP-RPT-LIST", ref: "04-my-reports §4.1.0c", title: "GET /api/reports 列表", kind: "pass" },
  { id: "GAP-RPT-PREVIEW", ref: "04-my-reports §4.1.0f", title: "ReportMarkdownPreview 深链策略", kind: "pass" },
  { id: "GAP-PORT-VAR-B", ref: "08-portfolio §8.4", title: "portfolio 变体 B 对照已发布 plan", kind: "pass" },
  { id: "GAP-FUND-KB03", ref: "09-fund-knowledge §9.2.0g", title: "fund KB-03 explore + waterfall", kind: "pass" },
  { id: "GAP-PORT-VISION", ref: "08-portfolio §8.1.3", title: "vision_parse 持仓截图 demo", kind: "pass" },
  { id: "GAP-PLAN-L0-POOL", ref: "07-allocation-plan §7.1", title: "plan L0 扩展池初筛", kind: "pass" },
  { id: "GAP-FK-UI", ref: "09-fund-knowledge §9.2.1", title: "fund-knowledge meta + tree API", kind: "pass" },
  { id: "GAP-FK-INDEX", ref: "09-fund-knowledge §9.2.0e", title: "SQLite FTS index.db + explore", kind: "pass" },
  { id: "GAP-L0-TUSHARE", ref: "02-settings-datasources §2.8.5", title: "L0 Tushare→AKShare→registry 链", kind: "pass" },
  { id: "GAP-DS-SETTINGS", ref: "02-settings-datasources §2.8.8", title: "数据源设置 API + 页", kind: "pass" },
  { id: "GAP-FK-PDF", ref: "09-fund-knowledge §9.2.0c", title: "PDF 上传转换管线", kind: "pass" },
  { id: "GAP-L0-HOLD", ref: "09-fund-analysis §9.1.8", title: "L0 top_holdings + dividend_history 字段", kind: "pass" },
  { id: "GAP-WL-01", ref: "09-fund-watchlist §9.3.4", title: "fund-watchlist API + 默认三只", kind: "pass" },
  { id: "GAP-SCH-UI", ref: "04-scheduled-tasks §4.2", title: "scheduled-jobs 页 + PATCH API", kind: "pass" },
  { id: "GAP-S14", ref: "04-scheduled-tasks §4.2.6 SCH-14", title: "s14 60s tick + 定时直发报告", kind: "pass" },
  { id: "GAP-FUND-ECHARTS", ref: "09-fund-analysis §9.1 FK-18-EC", title: "fund 报告 echarts 骨架 ≥6 + 预览渲染", kind: "pass" },
  { id: "GAP-RPT-SCHED", ref: "04-my-reports §4.1.7", title: "报告列表「定时生成」徽章", kind: "pass" },
  { id: "GAP-FK-FMT", ref: "09-fund-knowledge §9.2.0c FK-FMT-01", title: "上传表格/图片/DOCX 转换", kind: "pass" },
  { id: "GAP-USAGE", ref: "05-chat-shared §5.3.9", title: "侧栏使用说明抽屉 · C 端文案", kind: "pass" },
  { id: "GAP-S09", ref: "02-settings-memory §2.4", title: "聊天记忆 Preview + 刷新写库", kind: "pass" },
  { id: "GAP-EMB-FILTER", ref: "09-fund-knowledge §9.2.0g EMB-FILTER-01", title: "L1/L2/L3 层内 embedding 重排 + 设置可关", kind: "pass" },
  { id: "GAP-REPORT-READ", ref: "HARNESS §4.1 RPT-LINK-01", title: "report_read 深链解析 + Tool", kind: "pass" },
  { id: "GAP-ARTIFACT-READ", ref: "HARNESS §4.2 ARTIFACT-01", title: "artifact_read Tool + registry", kind: "pass" },
  { id: "GAP-MERMAID-01", ref: "01-global-design §1.3.3", title: "publish 前 mermaid 块校验", kind: "pass" },
  { id: "GAP-L0-FALLBACK", ref: "09-fund-analysis §9.1.8", title: "L0 降级 web_search 补行情", kind: "pass" },
  { id: "GAP-RPT-API-01", ref: "04-my-reports §4.1.5c", title: "reports open-folder / open-file API", kind: "pass" },
  { id: "GAP-RPT-LINK-01", ref: "04-my-reports §4.1.2", title: "四 Tab 复制链接 UI", kind: "pass" },
  { id: "GAP-RPT-EDIT-01", ref: "04-my-reports §4.1.1", title: "报告外部编辑 + 刷新 Preview", kind: "pass" },
  { id: "GAP-FK-API-01", ref: "09-fund-knowledge §9.2.9a.6", title: "FK open-folder / open-file API + UI", kind: "pass" },
  { id: "GAP-SH-08", ref: "05-chat-shared §5.1.2 SH-08", title: "workflow_locks 写流程互斥", kind: "pass" },
  { id: "GAP-RPT-LINK-TABS", ref: "HARNESS §4.1 RPT-LINK-01", title: "report_read 五 Tab router 注入", kind: "pass" },
  { id: "GAP-REHYDRATE-07", ref: "HARNESS §7.2", title: "§7 完整 rehydrate + execution_plan", kind: "pass" },
  { id: "GAP-MERMAID-PREVIEW", ref: "01-global-design §1.3.3", title: "Preview mermaid.run + 版本对齐", kind: "pass" },
  { id: "GAP-REACTIVE-COMPACT", ref: "HARNESS §6.4", title: "reactive_compact 一次重试", kind: "pass" },
  { id: "GAP-RPT-OVERLAY-01", ref: "04-my-reports §4.1.0h", title: "report_overlay patch/merge 闭环", kind: "pass" },
  { id: "GAP-L2-PGVECTOR", ref: "09-fund-knowledge §9.2.0f", title: "L2 Supabase pgvector 检索", kind: "pass" },
  { id: "GAP-KB03-FUND-QA", ref: "09-fund-analysis §9.1.10", title: "fund_qa KB-03 瀑布短答", kind: "pass" },
  { id: "GAP-FK-PDF-OCR", ref: "09-fund-knowledge FK-PDF-01", title: "PDF 扫描页 Vision OCR", kind: "pass" },
  { id: "GAP-FK-CITE", ref: "09-fund-knowledge §9.2.0e", title: "FK-CITE 深链 + metadata", kind: "pass" },
];
